a=float(input("Enter the value of a: "))
b=float(input("Enter the value of b: "))
equal=(a==b)
notEqual=(a!=b)
great=(a>b)
less=(a<b)
gtORequal=(a>=b)
lessORequal=(a<=b)
print("Check equal: ",equal)
print("Check not equal: ",notEqual)
print("Check greater than: ",great)
print("Check less than: ",less)
print("Check Greater than or equal: ",gtORequal)
print("Check less than or equal: ",lessORequal)

